"""Zagros portal HTML renderer — self-contained pages, zero external assets.

Everything is inlined: CSS (design tokens with dark/light), the QR codes as
inline SVG generated by our own ISO/IEC 18004 encoder, file downloads as
data URIs, and a few lines of JS for copy/theme/secret-reveal interactions.
The renderer is **driver-agnostic**: it walks DeliverySection/DeliveryArtifact
descriptors and never branches on core ids or protocol names.
"""
from __future__ import annotations

import base64
import html
import datetime

from app.cores.delivery import ArtifactKind, DeliverySection
from app.cores.qr import encode_matrix, to_svg
from app.portal.models import PageKind, PortalPage

# --------------------------------------------------------------------- #
# i18n (fa default, en fallback) — presentation strings only
# --------------------------------------------------------------------- #

_STRINGS: dict[str, dict[str, str]] = {
    "fa": {
        "subscription_of": "اشتراک",
        "status": "وضعیت", "used": "مصرف شده", "remaining": "باقی‌مانده",
        "expiry": "انقضا", "unlimited": "نامحدود", "no_expiry": "بدون تاریخ انقضا",
        "days_left": "روز باقی‌مانده", "expired": "منقضی شده",
        "copy": "کپی", "copied": "کپی شد ✓", "download_file": "دانلود فایل",
        "show_qr": "نمایش QR", "details": "جزئیات اتصال", "reveal": "نمایش",
        "hide": "پنهان", "download_app": "دانلود اپلیکیشن", "support": "پشتیبانی",
        "app_only_title": "اتصال فقط از طریق اپلیکیشن رسمی",
        "app_name_line": "اپلیکیشن رسمی: {app}",
        "app_only_body": "این اشتراک با لینک تحویل داده نمی‌شود. برای اتصال، "
                          "اپلیکیشن رسمی را نصب کنید و با نام کاربری و رمز عبور "
                          "اختصاصی اپ خود وارد شوید.",
        "app_only_no_apps": "لینک دانلود اپلیکیشن هنوز توسط مدیر سرویس تنظیم نشده است.",
        "stats_status": {"active": "فعال", "limited": "اتمام حجم", "expired": "منقضی",
                          "disabled": "غیرفعال", "on_hold": "در انتظار اتصال"},
        "online_now": "آنلاین", "offline": "آفلاین",
        "footer_powered": "قدرت‌گرفته از",
        "protocols_hint": "سرویس‌های شما",
        "your_username": "نام کاربری شما",
    },
    "en": {
        "subscription_of": "Subscription",
        "status": "Status", "used": "Used", "remaining": "Remaining",
        "expiry": "Expiry", "unlimited": "Unlimited", "no_expiry": "No expiry date",
        "days_left": "days left", "expired": "Expired",
        "copy": "Copy", "copied": "Copied ✓", "download_file": "Download file",
        "show_qr": "Show QR", "details": "Connection details", "reveal": "Reveal",
        "hide": "Hide", "download_app": "Download the app", "support": "Support",
        "app_only_title": "Connection via the official app only",
        "app_name_line": "Official app: {app}",
        "app_only_body": "This subscription is not delivered as a link. Install the "
                          "official app and sign in with your dedicated app username "
                          "and password.",
        "app_only_no_apps": "The app download link has not been configured by your "
                             "service provider yet.",
        "stats_status": {"active": "Active", "limited": "Data used up", "expired": "Expired",
                          "disabled": "Disabled", "on_hold": "Awaiting first connection"},
        "online_now": "Online", "offline": "Offline",
        "footer_powered": "Powered by",
        "protocols_hint": "Your services",
        "your_username": "Your username",
    },
}


def _t(page: PortalPage, key: str) -> str:
    table = _STRINGS.get(page.lang, _STRINGS["en"])
    return table.get(key, _STRINGS["en"].get(key, key))


def _esc(text: object) -> str:
    return html.escape(str(text), quote=True)


def _fmt_bytes(n: int | None, unlimited: str = "∞") -> str:
    if n is None:
        return unlimited
    value = float(n)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            if unit == "B":
                return f"{int(value)} {unit}"
            return f"{value:.2f} {unit}"
        value /= 1024
    return f"{value:.2f} PB"


def _fmt_date(dt: datetime.datetime | None, none_text: str) -> str:
    return dt.strftime("%Y/%m/%d") if dt else none_text


def _days_left(dt: datetime.datetime | None) -> int | None:
    if dt is None:
        return None
    delta = dt - datetime.datetime.now(datetime.timezone.utc)
    return delta.days


def _qr_svg(content: str) -> str:
    matrix = encode_matrix(content)
    return to_svg(matrix, module_px=6)


def _data_uri(mime: str, content: str) -> str:
    return f"data:{mime};base64,{base64.b64encode(content.encode('utf-8')).decode('ascii')}"


# --------------------------------------------------------------------- #
# design system (shared tokens with the Zagros admin dashboard)
# --------------------------------------------------------------------- #

_CSS = """
:root{
  --zg-primary:#4f7cff;--zg-primary-deep:#3b5fd9;--zg-accent:#22c59e;
  --zg-bg:#f4f7fc;--zg-card:#ffffff;--zg-card2:#eef2f9;--zg-text:#0f172a;
  --zg-muted:#64748b;--zg-border:#e2e8f0;--zg-danger:#ef4444;--zg-warn:#f59e0b;
  --zg-shadow:0 6px 24px rgba(15,23,42,.08);--zg-radius:18px;
}
html[data-theme="dark"]{
  --zg-bg:#0b1220;--zg-card:#121c30;--zg-card2:#182742;
  --zg-text:#e7edf7;--zg-muted:#8ea0bd;--zg-border:#233252;
  --zg-shadow:0 8px 28px rgba(0,0,0,.45);
}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:Vazirmatn,Tahoma,"Segoe UI",system-ui,sans-serif;background:var(--zg-bg);
  color:var(--zg-text);min-height:100vh;line-height:1.7;transition:background .25s,color .25s}
.wrap{max-width:880px;margin:0 auto;padding:20px 16px 72px}
.header{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 4px 24px}
.brand{display:flex;align-items:center;gap:10px;font-weight:800;font-size:20px;letter-spacing:.2px}
.brand svg{width:34px;height:34px}
.iconbtn{cursor:pointer;border:1px solid var(--zg-border);background:var(--zg-card);
  color:var(--zg-text);border-radius:12px;padding:8px 12px;font-size:14px}
.hero{background:linear-gradient(135deg,var(--zg-primary),var(--zg-primary-deep));
  border-radius:var(--zg-radius);padding:26px 22px;color:#fff;box-shadow:var(--zg-shadow);position:relative;overflow:hidden}
.hero::after{content:"";position:absolute;inset-inline-end:-60px;top:-60px;width:220px;height:220px;
  border-radius:50%;background:rgba(255,255,255,.12)}
.hero h1{font-size:22px;font-weight:800}
.hero .sub{opacity:.9;font-size:14px;margin-top:2px}
.pill{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:4px 14px;
  font-size:13px;font-weight:700}
.pill.ok{background:rgba(34,197,158,.18);color:#bff5e4}
.pill.bad{background:rgba(239,68,68,.2);color:#ffd4d4}
.pill.warn{background:rgba(245,158,11,.2);color:#ffe7bd}
.card{background:var(--zg-card);border:1px solid var(--zg-border);border-radius:var(--zg-radius);
  box-shadow:var(--zg-shadow);padding:20px;margin-top:18px}
.grid{display:grid;gap:14px;grid-template-columns:repeat(auto-fit,minmax(150px,1fr))}
.stat{background:var(--zg-card2);border-radius:14px;padding:14px}
.stat .k{font-size:12px;color:var(--zg-muted)}
.stat .v{font-size:17px;font-weight:800;margin-top:4px;word-break:break-all}
.bar{height:10px;background:var(--zg-card2);border-radius:999px;overflow:hidden;margin-top:14px}
.bar>div{height:100%;border-radius:999px;background:linear-gradient(90deg,var(--zg-accent),var(--zg-primary));
  transition:width .6s ease}
.section-title{display:flex;align-items:center;gap:10px;flex-wrap:wrap}
.section-title h2{font-size:17px;font-weight:800}
.chip{font-size:11px;font-weight:700;border:1px solid var(--zg-border);color:var(--zg-muted);
  border-radius:999px;padding:2px 10px;text-transform:uppercase;letter-spacing:.4px}
.artifact{border:1px solid var(--zg-border);border-radius:14px;padding:14px;margin-top:14px;background:var(--zg-card2)}
.artifact .lbl{font-size:13px;font-weight:700;margin-bottom:8px}
.linkbox{direction:ltr;text-align:left;word-break:break-all;background:var(--zg-card);
  border:1px dashed var(--zg-border);border-radius:10px;padding:10px;font-family:ui-monospace,Menlo,Consolas,monospace;
  font-size:12px;max-height:110px;overflow:auto}
.row{display:flex;gap:8px;align-items:center;justify-content:space-between;margin-top:10px;flex-wrap:wrap}
.btn{cursor:pointer;border:none;border-radius:10px;padding:9px 16px;font-weight:700;font-size:13px;
  font-family:inherit;background:var(--zg-primary);color:#fff;transition:background .2s}
.btn:hover{background:var(--zg-primary-deep)}
.btn.ghost{background:transparent;color:var(--zg-primary);border:1px solid var(--zg-primary)}
.qrbox{text-align:center;padding:14px;background:#fff;border-radius:14px;margin-top:10px}
.qrbox svg{width:220px;height:220px;max-width:100%}
table.fields{width:100%;border-collapse:collapse;font-size:14px}
table.fields td{padding:9px 6px;border-bottom:1px solid var(--zg-border);vertical-align:middle}
table.fields td.k{color:var(--zg-muted);white-space:nowrap;width:38%}
table.fields td.v{font-family:ui-monospace,Menlo,Consolas,monospace;word-break:break-all;direction:ltr;text-align:left}
.note{border-inline-start:4px solid var(--zg-primary);background:var(--zg-card2);
  border-radius:10px;padding:12px 14px;margin-top:12px;font-size:13.5px;color:var(--zg-muted)}
.mini{cursor:pointer;background:none;border:none;color:var(--zg-primary);font-size:12px;font-weight:700}
.apps{display:grid;gap:12px;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));margin-top:14px}
.appbtn{display:flex;align-items:center;gap:10px;justify-content:center;text-decoration:none;
  background:var(--zg-card2);border:1px solid var(--zg-border);color:var(--zg-text);
  border-radius:14px;padding:14px;font-weight:700;font-size:14px;transition:transform .15s}
.appbtn:hover{transform:translateY(-2px)}
.footer{text-align:center;color:var(--zg-muted);font-size:12px;margin-top:36px}
.footer a{color:var(--zg-primary);text-decoration:none}
details>summary{cursor:pointer;list-style:none}
details>summary::-webkit-details-marker{display:none}
@media(max-width:560px){.hero h1{font-size:19px}.grid{grid-template-columns:1fr 1fr}}
"""

_JS = """
function zgCopy(btn,text){
  const done=()=>{const t=btn.textContent;btn.textContent=btn.dataset.done||'✓';
    setTimeout(()=>btn.textContent=t,1400);};
  if(navigator.clipboard&&navigator.clipboard.writeText){
    navigator.clipboard.writeText(text).then(done).catch(()=>zgCopyFallback(text,done));
  }else{zgCopyFallback(text,done);}
}
function zgCopyFallback(text,done){
  const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';
  document.body.appendChild(ta);ta.select();try{document.execCommand('copy');}catch(e){}
  document.body.removeChild(ta);done();
}
function zgReveal(btn){
  const el=document.getElementById(btn.dataset.target);if(!el)return;
  const masked=el.dataset.masked==='1';
  if(masked){el.textContent=el.dataset.value;el.dataset.masked='0';btn.textContent=btn.dataset.hide;}
  else{el.textContent=el.dataset.mask;el.dataset.masked='1';btn.textContent=btn.dataset.show;}
}
function zgTheme(){
  const cur=document.documentElement.dataset.theme==='dark'?'light':'dark';
  document.documentElement.dataset.theme=cur;try{localStorage.setItem('zagros-theme',cur);}catch(e){}
}
(function(){try{const s=localStorage.getItem('zagros-theme');
  const prefer=window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';
  document.documentElement.dataset.theme=s||prefer;}catch(e){document.documentElement.dataset.theme='light';}})();
"""

_LOGO = """<svg viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
<rect x="2" y="2" width="44" height="44" rx="12" fill="#4f7cff"/>
<path d="M8 34 L18 16 L24 26 L30 13 L40 34 Z" fill="#fff"/>
<path d="M30 13 L35.5 22.5 L40 34 L30 34 Z" fill="#bcd0ff" opacity=".85"/>
<circle cx="37" cy="11" r="3.4" fill="#22c59e"/>
</svg>"""

_THEME_BTN = '<button class="iconbtn" onclick="zgTheme()" title="theme" aria-label="toggle theme">◐</button>'


def _status_pill(page: PortalPage) -> str:
    statuses = _STRINGS.get(page.lang, _STRINGS["en"])["stats_status"]
    label = statuses.get(page.user.status, page.user.status)
    tone = {"active": "ok", "on_hold": "warn"}.get(page.user.status, "bad")
    return f'<span class="pill {tone}">{_esc(label)}</span>'


def _copy_attr(text: str) -> str:
    """data-v attribute carrying URL-encoded text for zgCopy()."""
    from urllib.parse import quote

    return _esc(quote(text, safe=""))


def _render_link_artifact(page: PortalPage, artifact) -> str:
    url = artifact.content
    qr = ""
    if artifact.qr:
        qr = (
            f'<details><summary><button class="btn ghost" type="button">{_esc(_t(page, "show_qr"))}</button></summary>'
            f'<div class="qrbox">{_qr_svg(url)}</div></details>'
        )
    note = f'<div class="note">{_esc(artifact.note)}</div>' if artifact.note else ""
    return (
        f'<div class="artifact"><div class="lbl">{_esc(artifact.label)}</div>'
        f'<div class="linkbox">{_esc(url)}</div>'
        f'<div class="row"><div>{qr}</div>'
        f'<button class="btn" data-done="{_esc(_t(page, "copied"))}" '
        f'data-v="{_copy_attr(url)}" '
        f'onclick="zgCopy(this, decodeURIComponent(this.dataset.v))">'
        f"{_esc(_t(page, 'copy'))}</button></div>{note}</div>"
    )


def _render_artifact(page: PortalPage, artifact) -> str:
    if artifact.kind is ArtifactKind.LINK:
        return _render_link_artifact(page, artifact)
    if artifact.kind is ArtifactKind.FILE:
        href = _data_uri(artifact.mime, artifact.content)
        qr = ""
        if artifact.qr:
            qr = (
                f'<details><summary><button class="btn ghost" type="button">{_esc(_t(page, "show_qr"))}</button></summary>'
                f'<div class="qrbox">{_qr_svg(artifact.content)}</div></details>'
            )
        return (
            f'<div class="artifact"><div class="lbl">{_esc(artifact.label)}</div>'
            f'<div class="row"><a class="btn" download="{_esc(artifact.filename)}" '
            f'href="{href}">{_esc(_t(page, "download_file"))} · {_esc(artifact.filename)}</a>'
            f"<div>{qr}</div></div></div>"
        )
    if artifact.kind is ArtifactKind.FIELDS:
        rows: list[str] = []
        for i, field in enumerate(artifact.fields):
            fid = f"f{abs(hash((field.key, field.value))) % 10**8}_{i}"
            if field.secret:
                mask = "•" * min(10, max(6, len(field.value)))
                value_html = (
                    f'<span id="{fid}" data-value="{_esc(field.value)}" data-mask="{mask}" '
                    f'data-masked="1">{mask}</span> '
                    f'<button class="mini" data-target="{fid}" data-show="{_esc(_t(page, "reveal"))}" '
                    f'data-hide="{_esc(_t(page, "hide"))}" onclick="zgReveal(this)">{_esc(_t(page, "reveal"))}</button>'
                )
            else:
                value_html = _esc(field.value)
            copy_btn = ""
            if field.copyable:
                copy_btn = (
                    f'<button class="mini" data-done="{_esc(_t(page, "copied"))}" '
                    f'onclick="zgCopy(this, decodeURIComponent(this.dataset.v))" '
                    f'data-v="{_copy_attr(field.value)}">'
                    f'{_esc(_t(page, "copy"))}</button>'
                )
            rows.append(f"<tr><td class='k'>{_esc(field.label)}</td>"
                        f"<td class='v'>{value_html} {copy_btn}</td></tr>")
        note = f'<div class="note">{_esc(artifact.note)}</div>' if artifact.note else ""
        return (
            f'<div class="artifact"><div class="lbl">{_esc(artifact.label)}</div>'
            f'<table class="fields">{"".join(rows)}</table>{note}</div>'
        )
    # NOTE
    return f'<div class="note"><b>{_esc(artifact.label)}</b> — {_esc(artifact.note or "")}</div>'


def _render_section(page: PortalPage, section: DeliverySection) -> str:
    artifacts = "".join(_render_artifact(page, a) for a in section.artifacts)
    chips = f'<span class="chip">{_esc(section.protocol)}</span>'
    if section.engine:
        chips += f'<span class="chip">{_esc(section.engine)}</span>'
    note = f'<div class="note">{_esc(section.note)}</div>' if section.note else ""
    return (
        f'<div class="card"><div class="section-title"><h2>{_esc(section.title)}</h2>{chips}</div>'
        f"{note}{artifacts}</div>"
    )


def _render_portal(page: PortalPage) -> str:
    u = page.user
    unlimited = _t(page, "unlimited")
    ratio = u.usage_ratio
    bar = ""
    if ratio is not None:
        pct = int(round(ratio * 100))
        bar = f'<div class="bar" role="progressbar" aria-valuenow="{pct}"><div style="width:{pct}%"></div></div>'
    days = _days_left(u.expire_at)
    expiry_extra = ""
    if days is not None:
        expiry_extra = (
            f' <span style="opacity:.85">· {days} {_esc(_t(page, "days_left"))}</span>'
            if days >= 0 else f' <span style="opacity:.85">· {_esc(_t(page, "expired"))}</span>'
        )
    online = _t(page, "online_now") if u.online else ""
    hero_sub = f"{_esc(_t(page, 'subscription_of'))} <b>{_esc(u.username)}</b>"
    if online:
        hero_sub += f' · <span title="">{_esc(online)}</span>'

    stats = (
        f'<div class="grid">'
        f'<div class="stat"><div class="k">{_esc(_t(page, "status"))}</div>'
        f'<div class="v">{_status_pill(page)}</div></div>'
        f'<div class="stat"><div class="k">{_esc(_t(page, "used"))}</div>'
        f'<div class="v" dir="ltr">{_fmt_bytes(u.used_bytes, unlimited)}</div></div>'
        f'<div class="stat"><div class="k">{_esc(_t(page, "remaining"))}</div>'
        f'<div class="v" dir="ltr">{_fmt_bytes(u.remaining_bytes, unlimited)}</div></div>'
        f'<div class="stat"><div class="k">{_esc(_t(page, "expiry"))}</div>'
        f'<div class="v">{_fmt_date(u.expire_at, _t(page, "no_expiry"))}{expiry_extra}</div></div>'
        f"</div>{bar}"
    )
    sections_html = ""
    if page.sections:
        head = f'<div class="card"><div class="section-title"><h2>{_esc(_t(page, "protocols_hint"))}</h2></div></div>'
        sections_html = head + "".join(_render_section(page, s) for s in page.sections)
    notes = "".join(f'<div class="note">{_esc(n)}</div>' for n in page.notes)
    return f"""
<div class="hero"><h1>{_esc(page.brand)}</h1><div class="sub">{hero_sub}</div></div>
<div class="card">{stats}</div>
{notes}{sections_html}
"""


def _render_app_page(page: PortalPage) -> str:
    apps_html = ""
    if page.apps:
        buttons = "".join(
            f'<a class="appbtn" href="{_esc(app.url)}" rel="noopener">'
            f'<span>{_esc(app.name)}</span></a>'
            for app in page.apps
        )
        apps_html = f'<div class="apps">{buttons}</div>'
    else:
        apps_html = f'<div class="note">{_esc(_t(page, "app_only_no_apps"))}</div>'
    return f"""
<div class="hero"><h1>{_esc(page.brand)}</h1>
<div class="sub">{_esc(_t(page, 'subscription_of'))} <b>{_esc(page.user.username)}</b> · {_status_pill(page)}</div></div>
<div class="card" style="text-align:center;padding:34px 22px">
  <div style="font-size:44px">📲</div>
  <h2 style="margin:10px 0 6px">{_esc(_t(page, "app_only_title"))}</h2>
  <p style="color:var(--zg-muted);margin:0 0 8px">{_esc(_t(page, "app_name_line")).replace("{app}", _esc(page.app_name))}</p>
  <p style="color:var(--zg-muted);max-width:52ch;margin:0 auto">{_esc(_t(page, "app_only_body"))}</p>
  <div class="stat" style="max-width:320px;margin:18px auto 0">
    <div class="k">{_esc(_t(page, "your_username"))}</div>
    <div class="v">{_esc(page.user.username)}</div>
  </div>
</div>
<div class="card"><div class="section-title"><h2>{_esc(_t(page, "download_app"))}</h2></div>{apps_html}</div>
"""


def render_page_html(page: PortalPage) -> str:
    """Render a complete, self-contained HTML document."""
    body = _render_portal(page) if page.kind is PageKind.PORTAL else _render_app_page(page)
    support = ""
    if page.support_url:
        support = (
            f' · <a href="{_esc(page.support_url)}" rel="noopener">'
            f'{_esc(_t(page, "support"))}</a>'
        )
    footer = (
        f'<div class="footer">{_esc(_t(page, "footer_powered"))} '
        f"<b>{_esc(page.brand)}</b>{support}</div>"
    )
    return f"""<!doctype html>
<html lang="{_esc(page.lang)}" dir="{_esc(page.direction)}" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<title>{_esc(page.brand)} · {_esc(page.title or page.user.username)}</title>
<style>{_CSS}</style>
</head>
<body>
<div class="wrap">
<div class="header"><div class="brand">{_LOGO}<span>{_esc(page.brand)}</span></div>{_THEME_BTN}</div>
{body}
{footer}
</div>
<script>{_JS}</script>
</body>
</html>"""
